"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { AlertTriangle, CalendarDays, CheckCircle2, Plus } from "lucide-react";
import { useMemo, useState } from "react";

import {
  advanceReservePeriodStatusAction, assignRotationMemberAction, createReservePeriodAction, deletePhaseAction,
  deleteRotationGroupAction, deleteScheduleEventAction, editRotationBlockAction,
  generateRotationBlocksAction, publishReservePeriodAction, savePhaseAction,
  saveRotationGroupAction, saveRotationOverrideAction, saveScheduleEventAction,
} from "@/app/[teamSlug]/schedule/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { addCalendarDays, calendarDayDifference, eachCalendarDate, getDateInTimeZone } from "@/lib/kav/dates";
import { generateRotationBlocks } from "@/lib/kav/schedule-domain";
import { getDaySchedule, type ScheduleData } from "@/lib/kav/schedule";
import { cn } from "@/lib/utils";

const phaseLabels: Record<string, string> = { preparation: "הכנה", line: "קו", stand_down: "ירידה / התארגנות", processing: "זיכויים", other: "אחר" };
const eventLabels: Record<string, string> = { briefing: "תדריך", training: "אימון", family: "משפחות", processing: "זיכויים", changeover: "החלפה", other: "אחר" };

export function ScheduleView({ data, initialManage, view }: { data: ScheduleData; initialManage: boolean; view: string }) {
  const [manage, setManage] = useState(initialManage);
  const router = useRouter();
  const period = data.selectedPeriod;
  return <main className="mx-auto w-full max-w-7xl px-4 py-5 sm:px-6 lg:px-8">
    <header className="mb-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
      <div><Badge variant="secondary">{data.team.name}</Badge><h1 className="mt-3 text-3xl font-bold tracking-normal">לו״ז מבצעי</h1>{period ? <p className="mt-2 text-sm text-muted-foreground">{period.name} · {shortDate(period.starts_on)}–{shortDate(period.ends_on)}{period.location ? ` · ${period.location}` : ""}</p> : null}</div>
      <div className="flex flex-wrap gap-2">{data.periods.length ? <select aria-label="תקופת מילואים" className="h-10 rounded-md border bg-background px-3 text-sm" value={period?.id ?? ""} onChange={(event) => router.push(`/${data.team.slug}/schedule?period=${event.target.value}&view=${view}`)}>{data.periods.map((item) => <option key={item.id} value={item.id}>{item.name} · {statusLabel(item.status)}</option>)}</select> : null}{data.canManage ? <Button variant={manage ? "secondary" : "outline"} onClick={() => setManage((value) => !value)}><Plus className="size-4" />ניהול תקופה</Button> : null}</div>
    </header>
    {manage && data.canManage ? <Manager data={data} /> : null}
    {!period ? <Empty /> : <><nav className="mb-4 flex border-b"><Tab active={view === "month"} href={href(data, "month")}>חודש</Tab><Tab active={view === "agenda"} href={href(data, "agenda")}>אג׳נדה</Tab><Tab active={view === "rotations"} href={href(data, "rotations")}>סבבים</Tab></nav>{view === "month" ? <Month data={data} /> : view === "rotations" ? <Timeline data={data} /> : <Agenda data={data} />}</>}
  </main>;
}

function Empty() { return <section className="grid min-h-72 place-items-center border-y text-center"><div><CalendarDays className="mx-auto size-9 text-muted-foreground" /><h2 className="mt-3 text-lg font-semibold">אין עדיין תקופת מילואים</h2><p className="mt-2 text-sm text-muted-foreground">מנהל יכול ליצור תקופה חדשה ולהתחיל לבנות את הלו״ז.</p></div></section>; }
function Tab({ active, children, href }: { active: boolean; children: React.ReactNode; href: string }) { return <Link className={cn("border-b-2 px-5 py-3 text-sm font-medium", active ? "border-primary text-primary" : "border-transparent text-muted-foreground")} href={href}>{children}</Link>; }
function href(data: ScheduleData, view: string) { return `/${data.team.slug}/schedule?period=${data.selectedPeriod?.id}&view=${view}`; }

function Month({ data }: { data: ScheduleData }) {
  const period = data.selectedPeriod!; const focus = data.today >= period.starts_on && data.today <= period.ends_on ? data.today : period.starts_on;
  const monthStart = `${focus.slice(0, 7)}-01`; const gridStart = addCalendarDays(monthStart, -new Date(`${monthStart}T00:00:00Z`).getUTCDay());
  const dates = Array.from({ length: 42 }, (_, index) => addCalendarDays(gridStart, index));
  return <section className="overflow-x-auto rounded-lg border bg-card"><div className="border-b px-4 py-3 font-semibold">{new Intl.DateTimeFormat("he-IL", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${focus}T12:00:00Z`))}</div><div className="grid min-w-[760px] grid-cols-7 border-b bg-muted/40 text-center text-xs text-muted-foreground">{["א׳", "ב׳", "ג׳", "ד׳", "ה׳", "ו׳", "ש׳"].map((day) => <div className="p-2" key={day}>{day}</div>)}</div><div className="grid min-w-[760px] grid-cols-7">{dates.map((date) => { const day = getDaySchedule(data, date); return <Link className={cn("min-h-28 border-b border-l p-2 hover:bg-accent/40", date.slice(0, 7) !== focus.slice(0, 7) && "bg-muted/30 text-muted-foreground")} href={`/${data.team.slug}/schedule/${date}?period=${period.id}`} key={date}><div className="mb-2 flex justify-between"><span className={cn("grid size-7 place-items-center rounded-full text-sm", date === data.today && "bg-primary text-primary-foreground")}>{Number(date.slice(-2))}</span>{day.events.length ? <span className="mt-2 size-2 rounded-full bg-amber-500" /> : null}</div>{day.groups.slice(0, 2).map((group) => <div className="truncate text-xs" key={group.id}><b>{group.name}</b> · {stateLabel(group.block?.state)}</div>)}</Link>; })}</div></section>;
}

function Agenda({ data }: { data: ScheduleData }) {
  const period = data.selectedPeriod!;
  return <section className="divide-y rounded-lg border bg-card">{eachCalendarDate(period.starts_on, period.ends_on).map((date) => { const day = getDaySchedule(data, date); return <Link className="grid gap-3 p-4 hover:bg-muted/30 md:grid-cols-[12rem_1fr_12rem]" href={`/${data.team.slug}/schedule/${date}?period=${period.id}`} key={date}><div><b>{fullDate(date)}</b>{day.phase ? <div className="mt-1 text-xs text-muted-foreground">{day.phase.name}</div> : null}</div><div className="grid grid-cols-2 gap-3"><Summary label="בבסיס" count={day.expectedBase.length} groups={day.groups.filter((group) => group.block?.state === "base").map((group) => group.name)} /><Summary label="בבית" count={day.expectedHome.length} groups={day.groups.filter((group) => group.block?.state === "home").map((group) => group.name)} /></div><div className="text-sm text-muted-foreground">{day.events.slice(0, 2).map((event) => <div key={event.id}>{event.is_all_day ? "כל היום" : time(event.starts_at, data.team.timezone)} · {event.title}</div>)}</div></Link>; })}</section>;
}
function Summary({ count, groups, label }: { count: number; groups: string[]; label: string }) { return <div><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-sm"><b>{groups.join(", ") || "אין"}</b>{groups.length ? ` · ${count} אנשים` : ""}</div></div>; }

function Timeline({ data }: { data: ScheduleData }) {
  const period = data.selectedPeriod!; const days = calendarDayDifference(period.starts_on, period.ends_on) + 1;
  return <section className="rounded-lg border bg-card"><div className="border-b p-4"><h2 className="font-semibold">ציר סבבים</h2><p className="mt-1 text-xs text-muted-foreground">{days} ימים</p></div><div className="hidden overflow-x-auto p-4 md:block"><div className="min-w-[760px] space-y-4">{data.groups.map((group) => <div className="grid grid-cols-[8rem_1fr] items-center gap-3" key={group.id}><b>{group.name}</b><div className="relative h-14 rounded-md bg-muted">{data.blocks.filter((block) => block.rotation_group_id === group.id).map((block) => { const start = calendarDayDifference(period.starts_on, block.starts_on); const length = calendarDayDifference(block.starts_on, block.ends_on) + 1; return <div className={cn("absolute inset-y-1 grid place-items-center overflow-hidden rounded text-xs font-medium", block.state === "base" ? "bg-emerald-100 text-emerald-900" : "bg-sky-100 text-sky-900")} key={block.id} style={{ right: `${start / days * 100}%`, width: `${length / days * 100}%` }}>{stateLabel(block.state)}</div>; })}</div></div>)}</div></div><div className="divide-y md:hidden">{data.groups.map((group) => <div className="p-4" key={group.id}><b>{group.name}</b><div className="mt-2 space-y-2">{data.blocks.filter((block) => block.rotation_group_id === group.id).map((block) => <div className="flex justify-between rounded-md bg-muted p-3 text-sm" key={block.id}><span>{shortDate(block.starts_on)}–{shortDate(block.ends_on)}</span><State state={block.state} /></div>)}</div></div>)}</div></section>;
}

function Manager({ data }: { data: ScheduleData }) {
  const create = createReservePeriodAction.bind(null, data.team.slug); const period = data.selectedPeriod;
  return <section className="mb-6 border-y bg-card/60 py-5"><div className="mb-4 flex justify-between"><div><h2 className="text-lg font-semibold">ניהול תקופת מילואים</h2><p className="text-sm text-muted-foreground">התקופה נשמרת כטיוטה עד לפרסום.</p></div>{period ? <Badge variant="outline">{statusLabel(period.status)}</Badge> : null}</div><details className="border-b py-3" open={!period}><summary className="cursor-pointer font-medium">1. פרטי תקופה</summary><form action={create} className="mt-4 grid gap-3 md:grid-cols-4"><Field name="name" label="שם התקופה" required /><Field name="location" label="מיקום" /><Field name="starts_on" label="תאריך התחלה" type="date" required /><Field name="ends_on" label="תאריך סיום" type="date" required /><div><Button>יצירת תקופה כטיוטה</Button></div></form></details>{period ? <><Phases data={data} /><Groups data={data} /><Assignments data={data} /><Generator data={data} /><Blocks data={data} /><Overrides data={data} /><Events data={data} /><Publish data={data} /></> : null}</section>;
}

function Phases({ data }: { data: ScheduleData }) {
  const period = data.selectedPeriod!; const save = savePhaseAction.bind(null, data.team.slug); const remove = deletePhaseAction.bind(null, data.team.slug);
  return <Panel title={`2. שלבים (${data.phases.length})`}><div className="space-y-2">{data.phases.map((phase) => <details className="rounded-md border p-3" key={phase.id}><summary className="cursor-pointer"><b>{phase.name}</b> <small>{phaseLabels[phase.phase_type]} · {shortDate(phase.starts_on)}–{shortDate(phase.ends_on)}</small></summary><form action={save} className="mt-3 grid gap-2 md:grid-cols-6"><Period id={period.id} /><input type="hidden" name="id" value={phase.id} /><Field name="name" label="שם" defaultValue={phase.name} required /><Select name="phase_type" label="סוג" defaultValue={phase.phase_type} options={Object.entries(phaseLabels)} /><Field name="starts_on" label="התחלה" type="date" defaultValue={phase.starts_on} min={period.starts_on} max={period.ends_on} required /><Field name="ends_on" label="סיום" type="date" defaultValue={phase.ends_on} min={period.starts_on} max={period.ends_on} required /><Field name="sort_order" label="סדר" type="number" defaultValue={phase.sort_order} /><Button className="self-end" size="sm">עדכון</Button></form><form action={remove} className="mt-2"><input type="hidden" name="id" value={phase.id} /><Button size="sm" variant="ghost">מחיקה</Button></form></details>)}</div><form action={save} className="mt-3 grid gap-3 md:grid-cols-6"><Period id={period.id} /><Field name="name" label="שם" required /><Select name="phase_type" label="סוג" options={Object.entries(phaseLabels)} /><Field name="starts_on" label="התחלה" type="date" min={period.starts_on} max={period.ends_on} required /><Field name="ends_on" label="סיום" type="date" min={period.starts_on} max={period.ends_on} required /><Field name="sort_order" label="סדר" type="number" defaultValue={data.phases.length} /><div className="self-end"><Button>הוספת שלב</Button></div></form></Panel>;
}

function Groups({ data }: { data: ScheduleData }) {
  const period = data.selectedPeriod!; const save = saveRotationGroupAction.bind(null, data.team.slug); const remove = deleteRotationGroupAction.bind(null, data.team.slug);
  return <Panel title={`3. סבבים (${data.groups.length})`}><div className="grid gap-2 md:grid-cols-2">{data.groups.map((group) => <details className="rounded-md border p-3" key={group.id}><summary className="cursor-pointer"><b>{group.name}</b> <small>פתיחה: {stateLabel(group.initial_state)}</small></summary><form action={save} className="mt-3 grid gap-2 sm:grid-cols-4"><Period id={period.id} /><input type="hidden" name="id" value={group.id} /><Field name="name" label="שם" defaultValue={group.name} required /><Select name="initial_state" label="פתיחה" defaultValue={group.initial_state} options={[["base", "בסיס"], ["home", "בית"]]} /><Select name="color_token" label="צבע" defaultValue={group.color_token ?? "blue"} options={[["blue", "כחול"], ["green", "ירוק"], ["amber", "ענבר"], ["gray", "אפור"]]} /><Field name="sort_order" label="סדר" type="number" defaultValue={group.sort_order} /><Button size="sm">עדכון</Button></form><form action={remove} className="mt-2"><input type="hidden" name="id" value={group.id} /><Button size="sm" variant="ghost">מחיקה</Button></form></details>)}</div><form action={save} className="mt-3 grid gap-3 md:grid-cols-5"><Period id={period.id} /><Field name="name" label="שם הסבב" required /><Select name="initial_state" label="מצב פתיחה" options={[["base", "בסיס"], ["home", "בית"]]} /><Select name="color_token" label="צבע" options={[["blue", "כחול"], ["green", "ירוק"], ["amber", "ענבר"], ["gray", "אפור"]]} /><Field name="sort_order" label="סדר" type="number" defaultValue={data.groups.length} /><div className="self-end"><Button>הוספת סבב</Button></div></form></Panel>;
}

function Assignments({ data }: { data: ScheduleData }) {
  const assign = assignRotationMemberAction.bind(null, data.team.slug); const current = new Map(data.memberships.map((item) => [item.person_id, item]));
  return <Panel title="4. אנשי הסבב"><div className="grid gap-2">{data.people.filter((person) => person.is_active).map((person) => { const membership = current.get(person.id); return <form action={assign} className="grid items-end gap-2 rounded-md border p-2 md:grid-cols-[1fr_10rem_9rem_9rem_auto]" key={person.id}><Period id={data.selectedPeriod!.id} /><input type="hidden" name="person_id" value={person.id} /><span className="self-center truncate text-sm font-medium">{person.full_name}</span><Select name="rotation_group_id" label="סבב" required={false} defaultValue={membership?.rotation_group_id ?? ""} options={[["", "ללא סבב"], ...data.groups.map((group) => [group.id, group.name])]} /><Field name="starts_on" label="מתאריך" type="date" defaultValue={membership?.starts_on ?? ""} /><Field name="ends_on" label="עד תאריך" type="date" defaultValue={membership?.ends_on ?? ""} /><Button size="sm" variant="outline">שמירה</Button></form>; })}</div></Panel>;
}

function Generator({ data }: { data: ScheduleData }) {
  const period = data.selectedPeriod!; const action = generateRotationBlocksAction.bind(null, data.team.slug); const [anchor, setAnchor] = useState(data.config?.anchor_date ?? data.phases.find((phase) => phase.phase_type === "line")?.starts_on ?? period.starts_on); const [base, setBase] = useState(data.config?.base_days ?? 7); const [home, setHome] = useState(data.config?.home_days ?? 7);
  const preview = useMemo(() => generateRotationBlocks({ period: { startsOn: period.starts_on, endsOn: period.ends_on }, anchorDate: anchor, baseDays: base, homeDays: home, groups: data.groups.map((group) => ({ id: group.id, initialState: group.initial_state })) }), [anchor, base, data.groups, home, period]);
  const generated = data.blocks.some((block) => block.source === "generated");
  return <Panel title="5. דפוס סבבים ותצוגה מקדימה"><form action={action}><Period id={period.id} /><div className="grid gap-3 md:grid-cols-3"><Controlled label="תאריך עוגן" name="anchor_date" type="date" value={anchor} set={setAnchor} /><Controlled label="ימים בבסיס" name="base_days" type="number" value={String(base)} set={(value) => setBase(Number(value))} /><Controlled label="ימים בבית" name="home_days" type="number" value={String(home)} set={(value) => setHome(Number(value))} /></div><div className="mt-3 max-h-64 overflow-auto rounded-md border"><table className="w-full text-right text-sm"><tbody className="divide-y">{preview.slice(0, 20).map((block) => <tr key={`${block.groupId}-${block.sequenceNo}`}><td className="p-2">{data.groups.find((group) => group.id === block.groupId)?.name}</td><td className="p-2">{shortDate(block.startsOn)}–{shortDate(block.endsOn)}</td><td className="p-2"><State state={block.state} /></td></tr>)}</tbody></table></div>{generated ? <label className="mt-3 flex gap-2 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm"><input type="checkbox" name="confirm_replace" value="yes" required />יצירה מחדש תחליף בלוקים אוטומטיים. בלוקים ידניים יישמרו.</label> : null}<Button className="mt-3">יצירת הסבבים</Button></form></Panel>;
}

function Blocks({ data }: { data: ScheduleData }) {
  const action = editRotationBlockAction.bind(null, data.team.slug);
  return <Panel title="6. עריכת בלוקים"><div className="grid gap-2 lg:grid-cols-2">{data.blocks.map((block) => <form action={action} className="grid grid-cols-[1fr_6rem_8rem_auto] items-end gap-2 rounded-md border p-3" key={block.id}><input type="hidden" name="id" value={block.id} /><div className="text-sm"><b>{data.groups.find((group) => group.id === block.rotation_group_id)?.name}</b><div>{shortDate(block.starts_on)}–{shortDate(block.ends_on)}</div></div><Select defaultValue={block.state} label="מצב" name="state" options={[["base", "בסיס"], ["home", "בית"]]} /><Select label="תחולה" name="scope" options={[["only", "רק הבלוק"], ["following", "זה והבאים"]]} /><Button size="sm">עדכון</Button></form>)}</div></Panel>;
}

function Overrides({ data }: { data: ScheduleData }) {
  const action = saveRotationOverrideAction.bind(null, data.team.slug); const period = data.selectedPeriod!;
  return <Panel title="7. חריג סבב"><form action={action} className="grid gap-3 md:grid-cols-6"><Period id={period.id} /><Select name="person_id" label="איש צוות" options={data.people.filter((person) => person.is_active).map((person) => [person.id, person.full_name])} /><Select name="to_rotation_group_id" label="סבב זמני" options={data.groups.map((group) => [group.id, group.name])} /><Field name="starts_on" label="התחלה" type="date" min={period.starts_on} max={period.ends_on} required /><Field name="ends_on" label="סיום" type="date" min={period.starts_on} max={period.ends_on} required /><Field name="reason" label="סיבה" /><div className="self-end"><Button>הוספת חריג</Button></div></form></Panel>;
}

function Events({ data }: { data: ScheduleData }) {
  const save = saveScheduleEventAction.bind(null, data.team.slug); const remove = deleteScheduleEventAction.bind(null, data.team.slug); const period = data.selectedPeriod!;
  return <Panel title="8. אירועים"><div className="space-y-2">{data.events.map((event) => { const startsOn = getDateInTimeZone(data.team.timezone, new Date(event.starts_at)); const endsOn = event.ends_at ? getDateInTimeZone(data.team.timezone, new Date(event.ends_at)) : startsOn; return <details className="rounded-md border p-3 text-sm" key={event.id}><summary className="cursor-pointer"><b>{event.title}</b> · {eventLabels[event.event_type]} · {fullDate(startsOn)}</summary><form action={save} className="mt-3 grid gap-2 md:grid-cols-4"><Period id={period.id} /><input type="hidden" name="id" value={event.id} /><Field name="title" label="כותרת" defaultValue={event.title} required /><Select name="event_type" label="סוג" defaultValue={event.event_type} options={Object.entries(eventLabels)} /><Field name="starts_on" label="התחלה" type="date" defaultValue={startsOn} required /><Field name="starts_time" label="שעת התחלה" type="time" defaultValue={timeValue(event.starts_at, data.team.timezone)} /><Field name="ends_on" label="סיום" type="date" defaultValue={endsOn} /><Field name="ends_time" label="שעת סיום" type="time" defaultValue={event.ends_at ? timeValue(event.ends_at, data.team.timezone) : ""} /><Field name="location" label="מיקום" defaultValue={event.location ?? ""} /><Field name="notes" label="הערות" defaultValue={event.notes ?? ""} /><label className="flex items-end gap-2 pb-2"><input type="checkbox" name="is_all_day" defaultChecked={event.is_all_day} />כל היום</label><Button className="self-end" size="sm">עדכון</Button></form><form action={remove} className="mt-2"><input type="hidden" name="id" value={event.id} /><Button size="sm" variant="ghost">מחיקה</Button></form></details>; })}</div><form action={save} className="mt-3 grid gap-3 md:grid-cols-4"><Period id={period.id} /><Field name="title" label="כותרת" required /><Select name="event_type" label="סוג" options={Object.entries(eventLabels)} /><Field name="starts_on" label="תאריך התחלה" type="date" min={period.starts_on} max={period.ends_on} required /><Field name="starts_time" label="שעת התחלה" type="time" defaultValue="18:00" /><Field name="ends_on" label="תאריך סיום" type="date" /><Field name="ends_time" label="שעת סיום" type="time" defaultValue="19:00" /><Field name="location" label="מיקום" /><Field name="notes" label="הערות" /><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" name="is_all_day" />כל היום</label><div className="self-end"><Button>הוספת אירוע</Button></div></form></Panel>;
}

function Publish({ data }: { data: ScheduleData }) {
  const publish = publishReservePeriodAction.bind(null, data.team.slug); const advance = advanceReservePeriodStatusAction.bind(null, data.team.slug); const ready = data.validationIssues.length === 0; const period = data.selectedPeriod!;
  const nextLabel = period.status === "published" ? "הפעלת התקופה" : period.status === "active" ? "סיום התקופה" : period.status === "completed" ? "העברה לארכיון" : null;
  return <div className="pt-5"><div className={cn("flex gap-3 rounded-md border p-4", ready ? "border-emerald-300 bg-emerald-50" : "border-amber-300 bg-amber-50")}>{ready ? <CheckCircle2 className="size-5 text-emerald-700" /> : <AlertTriangle className="size-5 text-amber-700" />}<div><b>{ready ? "מוכן לפרסום" : `יש ${data.validationIssues.length} בעיות שצריך לפתור`}</b>{!ready ? <ul className="mt-2 list-disc pr-5 text-sm">{data.validationIssues.slice(0, 8).map((issue) => <li key={`${issue.code}-${issue.message}`}>{names(issue.message, data)}</li>)}</ul> : null}</div></div><div className="mt-3 flex gap-2">{period.status === "draft" ? <form action={publish}><Period id={period.id} /><Button disabled={!ready}>פרסום לצוות</Button></form> : null}{nextLabel ? <form action={advance}><Period id={period.id} /><Button variant="outline">{nextLabel}</Button></form> : null}</div></div>;
}

function Panel({ children, title }: { children: React.ReactNode; title: string }) { return <details className="border-b py-3"><summary className="cursor-pointer font-medium">{title}</summary><div className="mt-4">{children}</div></details>; }
function Field({ label, ...props }: React.ComponentProps<"input"> & { label: string }) { return <label className="grid gap-1.5 text-xs font-medium text-muted-foreground">{label}<Input {...props} /></label>; }
function Controlled({ label, set, value, ...props }: Omit<React.ComponentProps<"input">, "value" | "onChange"> & { label: string; set: (value: string) => void; value: string }) { return <label className="grid gap-1.5 text-xs font-medium text-muted-foreground">{label}<Input {...props} value={value} onChange={(event) => set(event.target.value)} /></label>; }
function Select({ defaultValue, label, name, options, required = true }: { defaultValue?: string; label: string; name: string; options: string[][]; required?: boolean }) { return <label className="grid gap-1.5 text-xs font-medium text-muted-foreground">{label}<select className="h-10 rounded-md border bg-background px-2 text-sm" defaultValue={defaultValue} name={name} required={required}>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>; }
function Period({ id }: { id: string }) { return <input type="hidden" name="reserve_period_id" value={id} />; }
function State({ state }: { state: string }) { return <Badge variant={state === "base" ? "success" : "secondary"}>{stateLabel(state)}</Badge>; }
function stateLabel(value?: string | null) { return value === "base" ? "בסיס" : value === "home" ? "בית" : "לא הוגדר"; }
function statusLabel(value: string) { return ({ draft: "טיוטה", published: "פורסם", active: "פעיל", completed: "הושלם", archived: "ארכיון" } as Record<string, string>)[value] ?? value; }
function shortDate(date: string) { return new Intl.DateTimeFormat("he-IL", { day: "2-digit", month: "2-digit", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`)); }
function fullDate(date: string) { return new Intl.DateTimeFormat("he-IL", { dateStyle: "full", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`)); }
function time(iso: string, zone: string) { return new Intl.DateTimeFormat("he-IL", { hour: "2-digit", minute: "2-digit", timeZone: zone }).format(new Date(iso)); }
function timeValue(iso: string, zone: string) { return new Intl.DateTimeFormat("en-GB", { hour: "2-digit", hourCycle: "h23", minute: "2-digit", timeZone: zone }).format(new Date(iso)); }
function names(message: string, data: ScheduleData) { for (const person of data.people) message = message.replace(person.id, person.full_name); for (const group of data.groups) message = message.replace(group.id, group.name); return message; }
